# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  workflow_dispatch:

name: db_manually

jobs:
  manually:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GKEY: ${{ secrets.GOOGLE_KEY }}
      credentals: ${{ secrets.CREDENTALS }}
      NEW_CLICKUP_KEY: ${{ secrets.NEW_CLICKUP_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        if: runner.os != 'Windows'
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-ubuntu22.04-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-ubuntu22.04-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "22.04"))')

      - name: Reinstall stringi package
        run: |
          echo 'if ("stringi" %in% installed.packages()[, "Package"]) { remove.packages("stringi") }' > reinstall_stringi.R
          echo 'install.packages("stringi", repos = Sys.getenv("RSPM"))' >> reinstall_stringi.R
          Rscript reinstall_stringi.R
        shell: bash

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: get clickup_data (run and capture log)
        run: |
          mkdir -p artifacts
          set -o pipefail
          Rscript -e 'source("R/db.R")' 2>&1 | tee artifacts/run.log
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clickup-results
          path: |
            artifacts/*.csv
            artifacts/*.json
            artifacts/*.rds
            artifacts/run.log

